language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.5-dev
  - nightly
  - pypy
  - pypy3

matrix:
  fast_finish: true
  # allow_failures:

sudo: false

install:
  - "pip install -r requirements.txt"

script:
  - nose2

after_success:
  - coverage run setup.py test
  - coveralls
  - codeclimate-test-reporter

notifications:
  email:
    - ryan@ryanparman.com
